<?php

/**
 * The plugin bootstrap file
 *
 * This file is read by WordPress to generate the plugin information in the plugin
 * admin area. This file also includes all of the dependencies used by the plugin,
 * registers the activation and deactivation functions, and defines a function
 * that starts the plugin.
 *
 * @link              https://www.journey.co.il
 * @since             1.0.0
 * @package           Rotem_Navigator
 *
 * @wordpress-plugin
 * Plugin Name:       Rotem Navigator
 * Plugin URI:        https://www.journey.co.il/rotem-navigator
 * Description:       The plugin add a navigator to posts so there are anchors to each H2 title from the top of the post.
 * Version:           1.0.0
 * Author:            Rotem Shmueli
 * Author URI:        https://www.journey.co.il
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       rotem-navigator
 * Domain Path:       /languages
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Currently plugin version.
 * Start at version 1.0.0 and use SemVer - https://semver.org
 * Rename this for your plugin and update it as you release new versions.
 */
define( 'ROTEM_NAVIGATOR_VERSION', '1.0.0' );

/**
 * The code that runs during plugin activation.
 * This action is documented in includes/class-rotem-navigator-activator.php
 */
function activate_rotem_navigator() {
	require_once plugin_dir_path( __FILE__ ) . 'includes/class-rotem-navigator-activator.php';
	Rotem_Navigator_Activator::activate();
}

/**
 * The code that runs during plugin deactivation.
 * This action is documented in includes/class-rotem-navigator-deactivator.php
 */
function deactivate_rotem_navigator() {
	require_once plugin_dir_path( __FILE__ ) . 'includes/class-rotem-navigator-deactivator.php';
	Rotem_Navigator_Deactivator::deactivate();
}

register_activation_hook( __FILE__, 'activate_rotem_navigator' );
register_deactivation_hook( __FILE__, 'deactivate_rotem_navigator' );

/**
 * The core plugin class that is used to define internationalization,
 * admin-specific hooks, and public-facing site hooks.
 */
require plugin_dir_path( __FILE__ ) . 'includes/class-rotem-navigator.php';

/**
 * Begins execution of the plugin.
 *
 * Since everything within the plugin is registered via hooks,
 * then kicking off the plugin from this point in the file does
 * not affect the page life cycle.
 *
 * @since    1.0.0
 */
function run_rotem_navigator() {

	$plugin = new Rotem_Navigator();
	$plugin->run();

}
run_rotem_navigator();


/** 
 * The actual plugin.
 */

function rotem_post_navigator_class() { 
	return '<div class="rotem-post-navigator"></div>';
} 

add_shortcode('rotemnavigator', 'rotem_post_navigator_class'); 

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class RotemNavigatorSettings {
	private $rotem_navigator_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'rotem_navigator_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'rotem_navigator_settings_page_init' ) );
	}

	public function rotem_navigator_settings_add_plugin_page() {
		add_options_page(
			'Rotem Navigator Settings', // page_title
			'Rotem Navigator Settings', // menu_title
			'manage_options', // capability
			'rotem-navigator-settings', // menu_slug
			array( $this, 'rotem_navigator_settings_create_admin_page' ) // function
		);
	}

	public function rotem_navigator_settings_create_admin_page() {
		$this->rotem_navigator_settings_options = get_option( 'rotem_navigator_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Rotem Navigator</h2>
			<p>You can leave the fields empty and the plugin will use default values.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'rotem_navigator_settings_option_group' );
					do_settings_sections( 'rotem-navigator-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function rotem_navigator_settings_page_init() {
		register_setting(
			'rotem_navigator_settings_option_group', // option_group
			'rotem_navigator_settings_option_name', // option_name
			array( $this, 'rotem_navigator_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'rotem_navigator_settings_setting_section', // id
			'Settings', // title
			array( $this, 'rotem_navigator_settings_section_info' ), // callback
			'rotem-navigator-settings-admin' // page
		);

		add_settings_field(
			'navigator_s_header_title_0', // id
			'Navigator\'s header title', // title
			array( $this, 'navigator_s_header_title_0_callback' ), // callback
			'rotem-navigator-settings-admin', // page
			'rotem_navigator_settings_setting_section' // section
		);

	}

	public function rotem_navigator_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['navigator_s_header_title_0'] ) ) {
			$sanitary_values['navigator_s_header_title_0'] = sanitize_text_field( $input['navigator_s_header_title_0'] );
		}


		return $sanitary_values;
	}

	public function rotem_navigator_settings_section_info() {
		
	}

	public function navigator_s_header_title_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="rotem_navigator_settings_option_name[navigator_s_header_title_0]" id="navigator_s_header_title_0" value="%s">',
			isset( $this->rotem_navigator_settings_options['navigator_s_header_title_0'] ) ? esc_attr( $this->rotem_navigator_settings_options['navigator_s_header_title_0']) : ''
		);
	}

}
if ( is_admin() )
	$rotem_navigator_settings = new RotemNavigatorSettings();

/* 
 * Retrieve this value with:
 * $rotem_navigator_settings_options = get_option( 'rotem_navigator_settings_option_name' ); // Array of All Options
 * $navigator_s_header_title_0 = $rotem_navigator_settings_options['navigator_s_header_title_0']; // Navigator\\\'s header title
 */


add_action('wp_head','rotem_navigator_simple_js');

function rotem_navigator_simple_js() {

	$rotem_navigator_settings_options = get_option( 'rotem_navigator_settings_option_name' );



	echo '
	<script>
		let rotemHeaderTitle = "Jump to:";
		let rotemWrappingClass = 0;
	</script>
	';

	if (isset($rotem_navigator_settings_options['navigator_s_header_title_0']) && !empty($rotem_navigator_settings_options['navigator_s_header_title_0'])) {
		echo '
		<script>
			rotemHeaderTitle = "'.htmlentities($rotem_navigator_settings_options['navigator_s_header_title_0']).'";
		</script>
	';
	}
	

}